# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecter', '0002_auto_20161214_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.CharField(db_index=True, default=0, max_length=30, verbose_name='Объём'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='interface',
            field=models.CharField(db_index=True, default=0, max_length=30, verbose_name='Интерфейс'),
            preserve_default=False,
        ),
    ]
