# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecter', '0005_auto_20161222_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='interface',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Интерфейс'),
        ),
    ]
