# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecter', '0007_auto_20161222_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
